

version: "3.8"

services:
  openai:
    container_name: openai
    restart: unless-stopped
    image: openai-production:2.0.0
    build:
      context: openai
      target: production
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - shared-network

networks:
  shared-network: